# Generated by Django 3.2.12 on 2022-03-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
