# Generated by Django 3.2.12 on 2022-03-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20220308_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='reservations.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
